apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lown
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-lown@sha256:acd40f50ef9667e5208d0cb8704d9717e0817ac15139fef0da2f46011e4f6fd2
        name: my-nodejs
        resources: {}
status: {}
